### ISSUE TITLE
remove interfaces annotations

### ISSUE THREAD

**Issue by Rohit-MyRG** [Rohit-MyRG/CoinWhisper#15]
Remove the @Component and @Service annotation of interfaces.
Please visit [Baeldung](https://www.baeldung.com/spring-service-annotation-placement) to understand Where Should the Spring @Service Annotation Be Kept.

Issue reference: All Services and Repositories interfaces.
Branch name: **bugfix/issue-\<issue-number\>**

Whoever wants to resolve this given issue should comment first.

**Comment by Rohit-MyRG** [comment]
Anyone who wants to resolve this issue?
@DevMrunalM @SLoharkar

**Comment by SLoharkar** [comment]
Hi, 
I take this

**Comment by Rohit-MyRG** [comment]
Great @SLoharkar very nice.
