### ISSUE TITLE
Modify Header.DocumentID for Template documents

### ISSUE THREAD

**Issue by Rohit-MyRG** [Rohit-MyRG/CoinWhisper#8]
Please go through the [FeatureTemplateServiceImpl](https://github.com/Rohit-MyRG/CoinWhisper/blob/dev/src/main/java/com/personal/financeManager/documentProcessor/services/impl/FeatureTemplateServiceImpl.java) java file or visit the Notion documentation.

Earlier **DocumentID** pattern was this: `<DocumentType:FeatureID:FeatureVarientID:TransactionID:Version>`
However, we realized that we don't need the TransactionID in the **Template Documents.**
So, please remove **TransactionID** completely from **DocumentID** and **Header**. pls do needful. 

Please create a new branch **"bugfix/issue-\<issue-number\>"** from **"dev"**

**Comment by Rohit-MyRG** [comment]
Please let me know who is going to work on this, only then i can assign this issue.
This will be **first come first serve**.

**Comment by DevMrunalM** [comment]
on what task you are asking??You have assign entity task on my name right??

**Comment by DevMrunalM** [comment]
okay i will do this in my local machine then when we will take meet then I
will use git bcoz I can do mistake in git so I not not sure about it

**Comment by Rohit-MyRG** [comment]
Great,
@DevMrunalM This is another task, I am assigning to you.
